development:
  adapter: postgresql
  database: giving_development
  username:
  password:
  host: localhost

test:
  adapter: postgresql
  database: giving_test
  username:
  password:
  host: localhost

production:
  adapter: postgresql
  database: giving_production
  username:
  password:
  host: localhost
